version: 0.0
os: linux
files:
  - source: Capstone_Project_One/Landing_Page.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: Capstone_Project_One/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: /restart_server
      timeout: 300
      runas: root
